### ISSUE TITLE
Request to add my three themes (Not an issue)

### ISSUE THREAD

**Issue by chris1111** [martinmilani/rEFInd-theme-collection#1]
Thanks for your [App](https://refind-themes-collection.netlify.app/)
Is this possible to add my themes
N0-1 [rEFInd-Shadow-IOS](https://github.com/chris1111/rEFInd-Shadow-IOS)
N0-2 [Shadow-rEFInd](https://github.com/chris1111/Shadow-rEFInd)
N0-3 [Icon-Set-DarkGrey-Refind](https://github.com/chris1111/Icon-Set-DarkGrey-Refind)
For the Badge you can use the first Background on my three repos
EDIT ***
I created the .webp images
[rEFInd-Shadow-IOS.webp](https://github.com/chris1111/rEFInd-Shadow-IOS/blob/main/Screenshot/rEFInd-Shadow-IOS.webp)
[Shadow-rEFInd.webp](https://github.com/chris1111/Shadow-rEFInd/blob/main/Screenshot/Shadow-rEFInd.webp)
[Icon-Set-DarkGrey-Refind.webp](https://github.com/chris1111/Icon-Set-DarkGrey-Refind/blob/main/Screenshot/Icon-Set-DarkGrey-Refind.webp)

Thanks

**Comment by martinmilani** [comment]
Hi! Nice themes!, Sure! I'll add it this weekend.

**Comment by chris1111** [comment]
> Hi! Nice themes!, Sure! I'll add it this weekend.

Thank you, I appreciate it

**Comment by chris1111** [comment]
I have a suggestion too, it would be to put the order of the most recent first.

**Comment by martinmilani** [comment]
I'll add some changes to the page along with your new themes soon.

**Comment by martinmilani** [comment]
If you could provide a short description it would be great!

**Comment by chris1111** [comment]
> If you could provide a short description it would be great!

it's the same description for the three themes, look on About
`Icon Set use with rEFInd and RefindPlus`
Please add another one here [rEFInd-Metal-Frame](https://github.com/chris1111/rEFInd-Metal-Frame)

**Comment by martinmilani** [comment]
Thanks! I'll add the new theme too.

**Comment by chris1111** [comment]
All of my theme have two background 
Please ad multiple background = true
